name: skin_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0  # Updated to latest compatible version
  html: ^0.15.0  # Downgraded to resolve the conflict
  vector_math: ^2.1.4
  flutter_appauth: ^5.0.0
  appwrite: ^14.0.0
  flutter_web_auth_2: ^5.0.0-alpha.2
  file_selector: ^1.0.0
  image_picker: ^0.8.9  # Updated to more recent stable version
  image_picker_for_web: ^2.0.0
  image_picker_web: ^4.0.0
  flutter_svg: ^2.1.0  # Updated for compatibility
  geolocator: ^14.0.0
  geolocator_web: ^4.1.3
  google_maps_flutter: ^2.12.0  # Updated to latest version
  url_launcher: ^6.3.1
  pdf: ^3.11.3
  permission_handler: ^12.0.0+1
  camera: ^0.11.0
  path_provider: ^2.1.5  # Changed to a compatible version
  google_ml_kit: ^0.20.0
  intl: ^0.20.2
  async: ^2.12.0
  device_info_plus: ^10.1.2  # Ensuring compatibility with appwrite
  material_color_utilities: ^0.11.1
  win32_registry: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/upload_icon.svg
    - assets/logo.png
    - assets/profile.png

dependency_overrides:
  html: ^0.15.0  # Forced resolution to fix version conflict
  device_info_plus: ^10.1.2  # Forced resolution to fix version conflict
  flutter_web_auth_2: ^3.1.2  # Version that works with dependencies
